runtime: python37

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
- url: /
  static_files: dist/resume/index.html
  upload: dist/resume/index.html

- url: /(.*)
  static_files: dist/resume/\1
  upload: dist/resume/(.*)
