name: Resume Pipeline

on:
  push:
    branches:
    - master
    - release/*

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Build Angular 8 Application
      run: npm run ng build -- --prod --output-path=dist
  gcloud-deploy:
    runs-on: ubuntu-latest
    needs: npm-build
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Deploy to gcloud
      uses: exelban/gcloud@271.0.0
      env:
        PROJECT_ID: web-resume-254010
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: app deploy