name: Resume Pipeline

on:
  push:
    branches:
    - master

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Build Angular 8 Application
      run: npm run ng build -- --prod
    - name: Upload compiled files
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
  gcloud-build:
    runs-on: ubuntu-latest
    needs: npm-build
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download compiled files
      uses: actions/download-artifact@v1
      with:
        name: dist
    - name: Build and deploy to GCR
      uses: actions-hub/gcloud@271.0.0
      env:
        PROJECT_ID: web-resume-254010
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLI: gcloud
      with:
        args: builds submit --tag gcr.io/web-resume-254010/www
  gcloud-deploy:
    runs-on: ubuntu-latest
    needs: gcloud-build
    steps:
    - name: Deliver service to Cloud Run
      uses: actions-hub/gcloud@271.0.0
      env:
        PROJECT_ID: web-resume-254010
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLI: gcloud
      with:
        args: run deploy resume-ui --image gcr.io/web-resume-254010/www --platform managed --region=europe-west1 --allow-unauthenticated
